"""The two things the visitor takes home: one printed page and one calendar reminder.

Both are built from the reading with plain Python. No model is involved once the facts are
grounded, so the card cannot say anything the check did not allow, and redaction is applied here as
well as upstream because this is the last place the text passes through before a printer.

The card is designed for the printer that actually stands behind a library counter, which is
monochrome. Nothing on it carries meaning in colour: urgency is a word plus a treatment that
survives greyscale, and the marks are numbered at the foot against the passages they came from, in
the same numbering the screen used, so a volunteer can say "number four" and both people find it.
"""

from __future__ import annotations

from datetime import UTC, date, datetime, time, timedelta
from html import escape

from icalendar import Alarm, Calendar, Event

from .locales import DeskWords, active
from .redact import redact
from .schemas import DeskReading, Explanation, Urgency

RTL_LANGUAGES = frozenset({"ar", "fa", "he", "ur", "ps"})

REMINDER_LEAD_DAYS = 3


def _urgency_word(words: DeskWords, urgency: Urgency) -> str:
    return {
        Urgency.OVERDUE: words.urgency_overdue,
        Urgency.DUE_SOON: words.urgency_due_soon,
        Urgency.AMPLE: words.urgency_ample,
        Urgency.UNKNOWN: words.urgency_unknown,
    }[urgency]


def is_rtl(language: str) -> bool:
    return language.split("-")[0].lower() in RTL_LANGUAGES


def desk_card_html(reading: DeskReading, today: date, *, case_id: str | None = None) -> str:
    """The one-page bilingual card, styled to print readably in black and white.

    The case id is printed only when there is a case, so a visitor who declined to be remembered
    takes home nothing that says otherwise.
    """
    words = active().words
    official, other = _explanations(reading, words.language)
    # The column is tagged with the language of the words actually printed in it, which is not
    # always the visitor's. A model asked for "nl, uk" can answer "uk-UA", and the fallback below
    # then puts the official-language text in the visitor's column: tagging that Dutch sentence
    # `lang="uk" dir="rtl"` tells a screen reader and a visitor something untrue about it.
    visitor = other.language
    direction = "rtl" if is_rtl(visitor) else "ltr"
    # Every model-written string on this page goes through the mask, the two in the band as much
    # as the ones in the rows. The runtime masks the whole response, so a string left unmasked
    # here is one the card prints and the console does not.
    who, what = redact(reading.sender_name), redact(reading.letter_type)
    case = (
        f'<p class="small"><strong>{escape(words.case_note.format(case_id=case_id))}</strong> '
        f"{escape(words.case_note_detail)}</p>"
        if case_id
        else ""
    )

    rows = "\n".join(
        _pair_row(question, official_text, visitor_text, visitor, direction)
        for question, official_text, visitor_text in (
            (words.question_what, official.what_is_this, other.what_is_this),
            (
                words.question_if_nothing,
                official.if_you_do_nothing,
                other.if_you_do_nothing,
            ),
            (words.question_by_when, official.by_when, other.by_when),
        )
    )
    steps = "\n".join(
        f'<li><span class="no">{step.order}</span>'
        f"<span>{escape(redact(step.dutch))}{_route(step.official_route)}</span>"
        f'<span class="r" lang="{escape(visitor)}" dir="{direction}">'
        f"{escape(redact(step.visitor))}{_route(step.official_route)}</span></li>"
        for step in reading.steps
    )
    handoff = (
        f'<p class="handoff"><strong>{escape(words.handoff_heading)}</strong> '
        f"{escape(reading.handoff.referral)}</p>"
        if reading.handoff.required
        else ""
    )

    return f"""<!doctype html>
<html lang="{escape(words.language)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{escape(words.card_description)}">
<meta name="generator" content="Plainletter, an AI system. This text was generated by an AI system
 and checked against the letter it was read from.">
<meta name="ai-generated" content="true">
<title>{escape(who)} - {escape(what)}</title>
<style>{_CARD_CSS}</style>
</head>
<body>
<div class="sheet">
  <div class="band">
    <div>
      <h1 class="who">{escape(who)}</h1>
      <div class="what">{escape(what)}</div>
    </div>
    <div class="ref">{escape(_reference(reading, words))}</div>
  </div>
  {_deadline_block(reading, words)}
  <div class="rows">{rows}</div>
  <div class="acts"><h2>{escape(words.actions_heading)}</h2><ol>{steps}</ol></div>
  {_key_block(reading, words)}
  <div class="foot">
    <div>
      {handoff}
      {case}
      <p class="small">{escape(words.disclaimer.format(date=active().format_date(today)))}</p>
      <p class="small">{escape(words.ai_disclosure)}</p>
    </div>
    <div>
      <p class="notes-label">{escape(words.notes_heading)}</p>
      <div class="notes"></div>
    </div>
  </div>
</div>
</body>
</html>
"""


def reminder_ics(reading: DeskReading, *, uid: str) -> str:
    """An all-day reminder on the deadline, with an alarm a few days ahead of it."""
    if reading.deadline is None:
        raise ValueError("a reminder needs a deadline; this reading has none")

    locale = active()
    words = locale.words
    deadline = reading.deadline.on
    calendar = Calendar()
    # The product identifier says an AI system wrote this file. A calendar entry is generated text
    # leaving the desk on its own, so the machine-readable marking travels in the one field every
    # calendar application reads.
    calendar.add("prodid", f"-//Plainletter AI system//{locale.reminder_region}//EN")
    calendar.add("version", "2.0")

    event = Event()
    event.add("uid", uid)
    # Masked for the same reason the card's band is: this file leaves the desk on its own.
    event.add("summary", f"{redact(reading.sender_name)}: {redact(reading.letter_type)}")
    event.add(
        "description",
        redact(
            words.reminder_deadline.format(date=locale.format_date(deadline))
            + " "
            + " ".join(step.dutch for step in reading.steps)
            + " "
            + words.ai_disclosure
        ),
    )
    event.add("dtstart", deadline)
    event.add("dtend", deadline + timedelta(days=1))
    # A fixed stamp keeps the file byte-identical for the same reading, which is what lets a test
    # compare one instead of comparing "roughly this".
    event.add("dtstamp", datetime.combine(deadline, time(9, 0), tzinfo=UTC))

    alarm = Alarm()
    alarm.add("action", "DISPLAY")
    alarm.add(
        "description",
        f"{redact(reading.sender_name)}: {words.reminder_alarm.format(days=REMINDER_LEAD_DAYS)}",
    )
    alarm.add("trigger", timedelta(days=-REMINDER_LEAD_DAYS))
    event.add_component(alarm)

    calendar.add_component(event)
    ical: bytes = calendar.to_ical()
    return ical.decode("utf-8")


def _explanations(reading: DeskReading, language: str) -> tuple[Explanation, Explanation]:
    by_language = {item.language: item for item in reading.explanations}
    official = by_language.get(language)
    other = by_language.get(reading.visitor_language, official)
    if official is None or other is None:
        raise ValueError(
            "a desk card needs an explanation in the letter's language and one in the visitor's"
        )
    return official, other


def _reference(reading: DeskReading, words: DeskWords) -> str:
    """The reference, masked exactly as the response masks it.

    The mask runs here for one reason only: the runtime walks every string in the response through
    it, this field included, so without it the printed card and the console show different numbers
    for the number the visitor has to quote. Two surfaces disagreeing about that in front of the
    person it belongs to is worse than either answer on its own.
    """
    reference = reading.facts.reference
    if reference is None:
        return words.reference_missing
    return words.reference.format(reference=redact(reference.value))


def _route(url: str | None) -> str:
    return f'<br><span class="route">{escape(_short_route(url))}</span>' if url else ""


def _short_route(url: str) -> str:
    """A route a person types off paper, so the scheme and the www prefix are noise."""
    return url.removeprefix("https://").removeprefix("http://").removeprefix("www.").rstrip("/")


def _deadline_block(reading: DeskReading, words: DeskWords) -> str:
    view = reading.deadline
    if view is None:
        return (
            f'<div class="deadline none"><div class="lead">{escape(words.deadline_missing)}'
            "</div></div>"
        )
    locale = active()
    word = _urgency_word(words, view.urgency)
    days = (
        words.days_left.format(days=view.days_left)
        if view.days_left >= 0
        else words.days_overdue.format(days=abs(view.days_left))
    )
    post_by = (
        words.post_by.format(date=locale.format_date(view.post_by))
        if view.post_by is not None
        else ""
    )
    lead = words.deadline_lead.format(date=locale.format_date(view.on))
    return f"""<div class="deadline {escape(view.urgency.value)}">
    <div><div class="lead">{escape(lead)}</div>
    <div class="sub">{escape(days)}{escape(post_by)}</div></div>
    <div class="state">{escape(word)}</div>
  </div>"""


def _key_block(reading: DeskReading, words: DeskWords) -> str:
    """The key at the foot: each numeral against the words on the letter it was drawn under.

    A gap prints as a broken rule with no number, which is how the card says the desk could not
    read something. There is no wording that could be mistaken for a fact, because there is no
    fact.
    """
    keys = "\n".join(
        f'<div class="k"><span class="n">{key.number}</span>'
        f"<span>{escape(redact(_one_line(key.text)))}</span></div>"
        for key in reading.letter.keys
    )
    gaps = "\n".join(
        f'<div class="k"><span class="broken"></span>'
        f"<span>{escape(gap.field)}: {escape(gap.ask_the_visitor)}</span></div>"
        for gap in reading.letter.gaps
    )
    if not keys and not gaps:
        return ""
    return f'<div class="keys"><h2>{escape(words.keys_heading)}</h2>{keys}{gaps}</div>'


def _one_line(text: str) -> str:
    return " ".join(text.split())


def _pair_row(question: str, official: str, visitor: str, language: str, direction: str) -> str:
    return (
        f'<div class="prow"><span class="q">{escape(question)}</span>'
        f"<span>{escape(redact(official))}</span>"
        f'<span class="r" lang="{escape(language)}" dir="{direction}">'
        f"{escape(redact(visitor))}</span></div>"
    )


# Print first, and monochrome first. Every urgency state carries a word plus a treatment that
# survives greyscale, because the only printer this page ever reaches has no colour to lose.
_CARD_CSS = """
@page { size: A4; margin: 12mm; }
* { box-sizing: border-box; }
body { font-family: "Atkinson Hyperlegible Next", system-ui, sans-serif;
       font-variant-numeric: tabular-nums; color: #1a1a1a; background: #fff;
       margin: 0; font-size: 11.5px; line-height: 1.5; }
.sheet { max-width: 190mm; margin: 0 auto; }
.band { border: 2.5px solid #1a1a1a; padding: 10px 13px; display: flex;
        justify-content: space-between; align-items: baseline; gap: 16px; }
.who { font-weight: 700; font-size: 19px; margin: 0; line-height: 1.25; }
.what { font-size: 12px; }
.ref { text-align: right; font-size: 12px; font-weight: 700; }
.deadline { border: 2.5px solid #1a1a1a; border-top: 0; padding: 10px 13px; display: flex;
            justify-content: space-between; align-items: center; gap: 16px; }
.deadline.due_soon { background-image:
  repeating-linear-gradient(-45deg, #d8d8d8 0 6px, transparent 6px 14px); }
.deadline.overdue { background-image:
  repeating-linear-gradient(-45deg, #b4b4b4 0 3px, transparent 3px 9px); }
.deadline.overdue .lead { text-decoration: line-through; }
.deadline .lead { font-weight: 700; font-size: 18px; }
.deadline .sub { font-size: 12px; }
.deadline .state { border: 2px solid #1a1a1a; background: #fff; padding: 5px 10px;
                   font-weight: 700; font-size: 11px; letter-spacing: .1em;
                   text-transform: uppercase; white-space: nowrap; }
.prow { display: grid; grid-template-columns: 1fr 1fr; gap: 3px 20px; padding: 11px 0;
        border-bottom: 1px solid #c9c9c9; }
.prow .q { grid-column: 1 / -1; font-size: 10px; font-weight: 700; text-transform: uppercase;
           letter-spacing: .1em; color: #4a4a4a; }
.r { text-align: right; }
.acts h2 { font-size: 13px; margin: 16px 0 8px; }
.acts ol { margin: 0; padding: 0; list-style: none; }
.acts li { display: grid; grid-template-columns: 20px 1fr 1fr; gap: 6px 20px; padding: 8px 0;
           border-top: 1px solid #c9c9c9; }
.acts li:first-child { border-top: 1.5px solid #1a1a1a; }
.no { width: 18px; height: 18px; background: #1a1a1a; color: #fff; font-size: 11px;
      font-weight: 700; line-height: 18px; text-align: center; }
.route { font-weight: 700; }
.keys { margin-top: 14px; border-top: 2.5px solid #1a1a1a; padding-top: 9px; }
.keys h2 { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: .1em;
           color: #4a4a4a; margin: 0 0 6px; }
.keys .k { display: grid; grid-template-columns: 20px 1fr; gap: 8px; padding: 3px 0;
           font-size: 10.5px; color: #333; }
.keys .n { width: 18px; height: 18px; border: 1px solid #1a1a1a; font-size: 10px;
           font-weight: 700; line-height: 16px; text-align: center; }
.keys .broken { width: 18px; border-top: 1px dashed #777; margin-top: 8px; }
.foot { margin-top: 12px; display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.handoff { border-left: 4px solid #1a1a1a; padding-left: 10px; font-size: 11px; margin: 0 0 8px; }
.notes-label { font-size: 9.5px; text-transform: uppercase; letter-spacing: .1em; color: #555;
               margin: 0 0 4px; }
.notes { border: 1px dashed #8a8a8a; height: 24mm; }
.small { font-size: 10px; color: #555; margin: 0; }
"""
